# ko's standard base image causes our integration tests to fail, due to lack of permission to read
# TLS CA certificates installed in the filesystem it looks like.
defaultBaseImage: grafana/alpine:3.15.0

builds:
  - id: mimir
    main: ./cmd/mimir
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Branch={{.Env.GIT_BRANCH}}
      - -X main.Revision={{.Env.GIT_REVISION}}
      - -X main.Version={{.Env.VERSION}}
      - --extldflags "-static" 
      - -s
      - -w
